# Generated by Django 2.2.14 on 2022-12-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('hora', models.TimeField()),
                ('institucion', models.CharField(max_length=70)),
                ('estado_reserva', models.CharField(choices=[('reservado', 'RESERVADO'), ('completada', 'COMPLETADA'), ('anulada', 'ANULADA'), ('no asisten', 'NO ASISTEN')], max_length=70)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
    ]
