# Generated by Django 2.2.14 on 2022-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_seminario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
    ]
